### ISSUE TITLE
Cannot add a worker call if workerfarm is ending.

### ISSUE THREAD

**Issue by hackerbin** [AdonisCommunity/adonis-blog-demo#51]
Having this error while ->  npm run build:dev
Details of errors:
    at WorkerFarm.addCall (/Users/robin/node/adonis-blog-demo/node_modules/@parcel/workers/src/WorkerFarm.js:194:13)
    at WorkerFarm.run (/Users/robin/node/adonis-blog-demo/node_modules/@parcel/workers/src/WorkerFarm.js:77:21)
    at Bundler.loadAsset (/Users/robin/node/adonis-blog-demo/node_modules/parcel-bundler/src/Bundler.js:577:35)
    at async Bundler.processAsset (/Users/robin/node/adonis-blog-demo/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/Users/robin/node/adonis-blog-demo/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
✨  Built in 770ms.

**Comment by williamtcastro** [comment]
Have you tried to delete the **package-lock.json** and rerunning **npm install** ?
